mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include(('push.urls', 'push'), namespace='push')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^slides/', include(('slides.urls', 'slides'), namespace='slides')),
    url(r'^presentation_editor/', include(('presentation_editor.urls', 'presentation_editor'),
                                          namespace='presentation_editor')),
    url(r'^question_editor/', include(('question_editor.urls', 'question_editor'),
                                      namespace='question_editor')),
    url(r'^admin/', admin.site.urls),
]

mysite/push/urls.py
# chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.presentation_list, name='presentation_list'),
    url(r'^push/$', views.presentation_list, name='presentation_list'),
    url(r'^push/presentation_list/$', views.presentation_list, name='presentation_list'),
    url(r'^push/presentation/(?P<room_name>[^/]+)/$', views.room, name='room'),
]

mysite/users/urls.py
# chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.log_in, name='index'),
    url(r'^log_in/$', views.log_in, name='log_in'),
    url(r'^log_out/$', views.log_out, name='log_out'),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^sign_up_teacher/$', views.sign_up_teacher, name='sign_up_teacher'),
]

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class ChannelsUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,)
    has_controls = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        ChannelsUser.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.channelsuser.save()

mysite/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.urls import reverse
from django.shortcuts import render, redirect

def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('push:presentation_list'))
        else:
            print(form.errors)
    return render(request, 'users/log_in.html', {'form': form})

@login_required
def log_out(request):
    logout(request)
    return redirect(reverse('push:presentation_list'))

def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('users:log_in'))
    return render(request, 'users/sign_up.html', {'form': form})

def sign_up_teacher(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save(commit=True)
            print(new_user.channelsuser.has_controls)
            new_user.channelsuser.has_controls = True
            print(new_user.channelsuser.has_controls)
            new_user.save()
            return redirect(reverse('users:log_in'))
    return render(request, 'users/sign_up_teacher.html', {'form': form})

mysite/users/templates/users/_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Alexander Arias González">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <title>Users</title>
    <style>
        body {
            margin-top: 125px;
        }

        .nav {
            margin-top: 28px;
        }
    </style>
    {% block style %}{% endblock style %}
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand logo-nav" style="padding: 0!important" href="#">
                    <img src="https://campusvirtual.univalle.edu.co/moodle/theme/crisp/pix/logo-footer.png" width="55" height="78" alt="">
                </a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/push/presentation_list">Lista de Presentaciones</a>
                    </li>
                    {% if request.user.is_authenticated and request.user.channelsuser.has_controls %}
                    <li>
                        <a href="/presentation_editor">Editor de Presentaciones</a>
                    </li>
                    <li>
                        <a href="/question_editor">Editor de Preguntas</a>
                    </li>
                    {% endif %}
                    <li>
                        {% if request.user.is_authenticated %}
                        <a href="/users/log_out">Logout</a>
                        {% else %}
                        <a href="/users/log_in">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <br>
        {% block content %}{% endblock content %}
    </div>
    <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
    {% block script %}{% endblock script %}
</body>
</html>

mysite/users/templates/users/log_in.html
{% extends 'users/_base.html' %}

{% block content %}
    <form action="{% url 'users:log_in' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit">Ingresar</button>
    </form>
    <p>No tienes una cuenta? <a href="{% url 'users:sign_up' %}">Registrate</a></p>
{% endblock content %}

mysite/users/templates/users/sign_up.html
{% extends 'users/_base.html' %}

{% block style %}
    <style>
        .errorlist {
            color: red;
        }
    </style>
{% endblock style %}

{% block content %}
    <form action="{% url 'users:sign_up' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        {% if form.errors %}
            {{ form.errors }}
        {% endif %}
        <button type="submit">Registrar</button>
        <p>Ya tienes una cuenta? <a href="{% url 'users:log_in' %}">Ingresa!</a></p>
    </form>
{% endblock content %}

mysite/users/templates/users/sign_up_teacher.html
{% extends 'users/_base.html' %}

{% block style %}
    <style>
        .errorlist {
            color: red;
        }
    </style>
{% endblock style %}

{% block content %}
    <form action="{% url 'users:sign_up_teacher' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        {% if form.errors %}
            {{ form.errors }}
        {% endif %}
        <button type="submit">Registrar</button>
        <p>Ya tienes una cuenta? <a href="{% url 'users:log_in' %}">Ingresa!</a></p>
    </form>
{% endblock content %}